// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Segurity.Models;

namespace Segurity.Migrations
{
    [DbContext(typeof(SegurityContext))]
    [Migration("20191129141515_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Segurity.Models.Persona", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Nombre");

                    b.HasKey("ID");

                    b.ToTable("Persona");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Apellido = "Perez",
                            Nombre = "Juan"
                        },
                        new
                        {
                            ID = 2,
                            Apellido = "Meyer",
                            Nombre = "Camila"
                        },
                        new
                        {
                            ID = 3,
                            Apellido = "Fernandez",
                            Nombre = "Maria"
                        },
                        new
                        {
                            ID = 4,
                            Apellido = "Rodriguez",
                            Nombre = "Jorge"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
